#!/usr/bin/env bash
# run_review.sh — POST a review packet to the DeepSeek API; write the response.
#
# Single provider: DeepSeek (api.deepseek.com, OpenAI-compatible). Trimmed to
# DeepSeek-only 2026-06-10 (PO call). See
# docs/adr/0011-multi-provider-review-cascade.md §Addendum 2026-06-10 and
# docs/adr/0001-direct-gemini-api-for-reviews.md.
#
# Usage:
#   ./scripts/run_review.sh <slug> [model] [date]
#
# When [date] is omitted the script globs review_packets/*-<slug>.md and picks
# the newest match (lexicographic on YYYY-MM-DD == newest chronologically).
#
# Examples:
#   ./scripts/run_review.sh simulator-pump
#   ./scripts/run_review.sh simulator-pump deepseek-chat
#   ./scripts/run_review.sh simulator-pump deepseek-reasoner 2026-05-24
#
# Requires: curl, jq, $DEEPSEEK_API_KEY (https://platform.deepseek.com/api_keys).
# A gitignored scripts/review_keys.local.sh is sourced if present.

set -euo pipefail

_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "$_here/review_keys.local.sh" ]] && source "$_here/review_keys.local.sh"

slug="${1:?Usage: $0 <slug> [model] [date]}"
model="${2:-deepseek-reasoner}"

if [[ -n "${3-}" ]]; then
  date="$3"
  packet="review_packets/${date}-${slug}.md"
else
  shopt -s nullglob
  candidates=(review_packets/*-"${slug}".md)
  shopt -u nullglob
  if [[ ${#candidates[@]} -eq 0 ]]; then
    echo "No packet found for slug '${slug}' under review_packets/. Tried glob '*-${slug}.md'. Pass [date] if the slug differs." >&2
    exit 1
  fi
  IFS=$'\n' read -r -d '' -a sorted < <(printf '%s\n' "${candidates[@]}" | sort -r && printf '\0')
  packet="${sorted[0]}"
  filename="${packet##*/}"
  filename="${filename%.md}"
  date="${filename%-${slug}}"
  echo "Auto-selected packet: ${packet##*/}" >&2
fi
response="review_responses/${date}-${slug}.md"

[[ -f "$packet" ]] || { echo "Packet not found: $packet" >&2; exit 1; }
[[ -n "${DEEPSEEK_API_KEY:-}" ]] || {
  echo "DEEPSEEK_API_KEY env var not set. Get one at https://platform.deepseek.com/api_keys" >&2
  exit 1
}

mkdir -p "$(dirname "$response")"

body=$(jq -n --arg model "$model" --rawfile prompt "$packet" \
  '{model: $model, messages: [{role: "user", content: $prompt}]}')

url="https://api.deepseek.com/chat/completions"

http_response=$(curl -sS -w "\n%{http_code}" -X POST "$url" \
  -H "Content-Type: application/json; charset=utf-8" \
  -H "Authorization: Bearer ${DEEPSEEK_API_KEY}" \
  --data-binary "$body")

http_code=$(echo "$http_response" | tail -n1)
body_response=$(echo "$http_response" | sed '$d')

if [[ "$http_code" != "200" ]]; then
  echo "DeepSeek API returned HTTP $http_code:" >&2
  echo "$body_response" >&2
  exit 1
fi

text=$(echo "$body_response" | jq -r '.choices[0].message.content // empty')
if [[ -z "$text" ]]; then
  echo "Empty response from DeepSeek. Raw:" >&2
  echo "$body_response" >&2
  exit 1
fi

{
  printf "%s" "$text"
  printf "\n\n---\n_Generated by **deepseek** (\`%s\`) on %s._\n" "$model" "$(date '+%Y-%m-%d %H:%M:%S')"
} > "$response"
echo "Wrote $response (${#text} chars, provider=deepseek, model=$model)"
